version: "3.7" 
services:
  php:
    build:
      context: .
    image: php_api_series
    container_name: api_series
    ports:
      - "8000:8000"
    volumes:
      - ".:/var/www/html/" 
    command: php -S 0.0.0.0:8000 -t public/